# Generated by Django 3.2.12 on 2022-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of site-wide variable', max_length=200)),
                ('value', models.JSONField(blank=True, help_text='Value of site-wide variable that scripts can reference - must be valid JSON', null=True)),
            ],
        ),
    ]
