# Generated by Django 3.2.12 on 2022-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarylink',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='temporarylink',
            name='id',
        ),
        migrations.AlterField(
            model_name='temporarylink',
            name='key',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
