# Generated by Django 3.2.12 on 2022-03-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploader', '0002_auto_20220303_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarylink',
            name='key',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Key'),
        ),
    ]
